# Site settings
name: "Allison Liu"
description: "azn@allisonznliu.com"
meta_description: ""
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: "bio-photo.jpg"
  greetings: "Hi! My name is Allison Liu. I'm passionate about improving sustainability through uncovering and understanding patterns in data."
favicon: "assets/images/favicon.ico"
resume: "Resume_AllisonLiu.pdf"
baseurl:
production_url: https://allisonznliu.com/
# Add your GA Tracking Id
ga_analytics: G-1HG83XG8WR

# Social links
github: "aznliu"
linkedin: "allisonznliu"

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Projects
    url: /projects
  - text: Publications
    url: /publications

# Required Plugins
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-paginate
  # - jekyll-tagsgenerator

collections:
  tags:
    output: true
    order:
      - machinelearning.md
      - appm.md
      - algorithms.md
      - engineering.md
      - sciencewriting.md
      - climbing.md

# Pagination
# paginate: 10
# paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
